
- type: job
  id: MedicalBorg
  setPreference: false # ERRORGATE: only HumanError is selectable
  name: job-name-medical-borg
  description: job-description-medical-borg
  playTimeTracker: JobMedicalBorg
  canBeAntag: false
  icon: JobIconMedicalBorg
  supervisors: job-supervisors-cmo
  jobEntity: BorgChassisMedical
