- type: entity
  parent: BlueshieldAmmunitionBox
  id: BlueshieldAmmunitionBoxFilled
  suffix: Filled
  components:
  - type: StorageFill
    contents:
    - id: AmmoBox357Magnum
      amount: 2
    - id: AmmoBox357MagnumFlash
    # - id: AmmoBox357MagnumEMP
    - id: Magazine357MagnumLeverRifleEmpty
      amount: 2
