## Static recipes

- type: latheRecipePack
  id: SecurityEquipmentStatic
  recipes:
  - ClothingEyesHudSecurity
  - ForensicPad
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties
  # EE EDIT START
  - HoloprojectorSecurity
  - TelescopicShield
  - BolaEnergy
  # EE EDIT END

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: SecurityPracticeStatic
  recipes:
  - BoxShotgunPractice
  - AmmoBox762x39Practice
  - AmmoBox357MagnumPractice
  - AmmoBox9x19Practice
  - AmmoBox556x45Practice
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  - WeaponFlareGunSecurity
  # EE EDIT START
  # - AmmoBoxCaselessRiflePractice - WD EDIT
  # - MagazineBoxSpecialPractice - WD EDIT
  - Magazine6mmCaselessPractice
  # - Magazine6mmCaselessShortPractice - WD EDIT
  # - MagazinePistol6mmCaselessPractice - WD EDIT
  # EE EDIT END

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: SecurityAmmoStatic
  recipes:
  - BoxLethalshot
  - BoxShotgunSlug
  - AmmoBox762x39
  - AmmoBox357Magnum
  - AmmoBox9x19
  - AmmoBox556x45
  - Magazine762x39
  - Magazine762x39Empty
  - Magazine9x19
  - Magazine9x19Empty
  - Magazine9x19SubMachineGun
  - Magazine9x19SubMachineGunEmpty
  - Magazine9x19SubMachineGunTopMounted
  - Magazine9x19SubMachineGunTopMountedEmpty
  - Magazine556x45
  - Magazine556x45Empty
  - MagazineShotgun
  - MagazineShotgunEmpty
  - MagazineShotgunSlug
  - SpeedLoader357Magnum
  - SpeedLoader357MagnumEmpty
  # EE EDIT START
  - BoxBeanbag
  - BoxShellTranquilizer
  - BoxShotgunBirdshot
  - BoxShotgun00Buckshot
  - BoxShotgun0000Buckshot
  - BoxShotgunLumen
  # - AmmoBoxCaselessRifle - WD EDIT
  # - MagazineBoxSpecial - WD EDIT
  - Magazine6mmCaseless
  # - Magazine6mmCaselessShort - WD EDIT
  # - Magazine762x39LowCapacity - WD EDIT
  # - Magazine762x39LowCapacityEmpty - WD EDIT
  - Magazine762x39MarkOne
  - Magazine762x39MarkOneEmpty
  - Magazine45ACP
  - Magazine45ACPEmpty
  # - Magazine357MagnumLeverRifle - WD EDIT
  # - Magazine357MagnumLeverRifleEmpty - WD EDIT
  # - MagazineNovaliteC1 - WD EDIT
  # - MagazineNovaliteC1Empty - WD EDIT
  # - MagazinePistol6mmCaseless - WD EDIT
  # - Magazine9x19Special - WD EDIT
  - MagazineShotgunBeanbag
  - MagazineUSP45ACP
  - MagazineUSP45ACPEmpty
  # - SpeedLoaderRifleHeavy - WD EDIT
  # - SpeedLoaderRifleHeavyEmpty - WD EDIT
  # - SpeedLoaderSpecial - WD EDIT
  # EE EDIT END

- type: latheRecipePack
  id: SecurityWeaponsStatic
  recipes:
  - Flash
  - Stunbaton
  - CombatKnife
  - RiotShield
  # EE EDIT START
  # - WeaponRifleNovaliteC1 - WD EDIT
  # - WeaponRifleGestio - WD EDIT
  # EE EDIT END


## Dynamic recipes

- type: latheRecipePack
  id: SecurityEquipment
  recipes:
  - ClothingBackpackElectropack
  # - HoloprojectorSecurity - EE EDIT: moved to static
  - PortableRecharger
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  # - TelescopicShield - EE EDIT: moved to static
  # WD EDIT START
  - SmallBasicFluxCore
  - BasicFluxCore
  - SmallAdvancedFluxCore
  - AdvancedFluxCore
  # WD EDIT END

- type: latheRecipePack
  id: SecurityBoards
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard
  # EE EDIT START
  - WeaponEnergyTurretAIMachineCircuitboard
  - WeaponEnergyTurretStationMachineCircuitboard
  - WeaponEnergyTurretAIControlPanelElectronics
  - WeaponEnergyTurretStationControlPanelElectronics
  # EE EDIT END

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: SecurityExplosives
  recipes:
  - ExplosivePayload
  - GrenadeBlast
  - GrenadeEMP
  - GrenadeFlash
  - MagazineGrenadeEmpty

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: SecurityAmmo
  recipes:
  # - BoxBeanbag - EE EDIT: moved to static
  - BoxShotgunIncendiary
  - BoxShotgunUranium
  # - BoxShellTranquilizer - EE EDIT: moved to static
  - AmmoBox762x39Incendiary
  - AmmoBox762x39Uranium
  - AmmoBox357MagnumIncendiary
  - AmmoBox357MagnumUranium
  - AmmoBox9x19Incendiary
  - AmmoBox9x19Uranium
  - AmmoBox556x45Incendiary
  - AmmoBox556x45Uranium
  - Magazine762x39Incendiary
  - Magazine762x39Uranium
  - Magazine9x19Incendiary
  - Magazine9x19Uranium
  - Magazine9x19SubMachineGunIncendiary
  - Magazine9x19SubMachineGunUranium
  - Magazine556x45Incendiary
  - Magazine556x45Uranium
  # - MagazineShotgunBeanbag - EE EDIT: moved to static
  - MagazineShotgunIncendiary
  - SpeedLoader357MagnumIncendiary
  - SpeedLoader357MagnumUranium
  # EE EDIT START
  - ShellSoulbreaker
  - AmmoBoxCaselessRifleIncendiary
  - AmmoBoxCaselessRifleShrapnel
  - AmmoBoxCaselessRifleUranium
  - AmmoBox762x39Shrapnel
  - AmmoBox357MagnumShrapnel
  - AmmoBox9x19Shrapnel
  - AmmoBox556x45Shrapnel
  - MagazineBoxSpecialIncendiary
  - MagazineBoxSpecialUranium
  - MagazineBoxSpecialMindbreaker
  - Magazine6mmCaselessShrapnel
  - Magazine6mmCaselessIncendiary
  - Magazine6mmCaselessUranium
  - Magazine762x39Shrapnel
  - Magazine45ACPIncendiary
  - Magazine45ACPShrapnel
  - Magazine45ACPUranium
  - Magazine9x19Shrapnel
  - Magazine9x19SubMachineGunShrapnel
  - Magazine556x45Shrapnel
  - MagazineUSP45ACPUranium
  - MagazineUSP45ACPIncendiary
  - MagazineUSP45ACPShrapnel
  - SpeedLoaderRifleHeavyIncendiary
  - SpeedLoaderRifleHeavyUranium
  # EE EDIT END
  # WD EDIT START
  - BoxBreach
  - BoxFrag
  - BoxLaser
  - Magazine762x39LowCapacity
  - Magazine762x39LowCapacityEmpty
  - SpeedLoaderRifleHeavy
  - SpeedLoaderRifleHeavyEmpty
  - Magazine357MagnumLeverRifle
  - Magazine357MagnumLeverRifleEmpty
  - MagazineNovaliteC1
  - MagazineNovaliteC1Empty
  - MagazineShotgunBreach
  - MagazineShotgunFrag
  - MagazineShotgunLaser
  # WD EDIT END

- type: latheRecipePack
  id: SecurityWeapons
  recipes:
  - Truncheon
  - WeaponAdvancedLaser
  - WeaponDisabler
  - WeaponDisablerSMG
  - WeaponLaserCannon
  - WeaponLaserCarbine
  - WeaponXrayCannon
  # EE EDIT START
  - Terminus
  - WeaponEnergyGun
  - WeaponEnergyGunMini
  - WeaponEnergyGunPistol
  - WeaponGunLaserCarbineAutomatic
  # - EnergySword - WD EDIT
  # - EnergySwordDouble - WD EDIT
  # - EnergyCutlass - WD EDIT
  # - WeaponSubMachineGunFPA90 - WD EDIT
  - WeaponSubMachineGunBRDIR25
  - WeaponPistolMk58
  - WeaponPistolN1984
  # - WeaponPistolViper - WD EDIT
  # - WeaponPistolCobra - WD EDIT
  - WeaponPistolUniversal
  # EE EDIT END
  # WD EDIT START
  - WeaponSecurityRiotLauncher
  - WeaponRifleNovaliteC1
  - WeaponRifleGestio
  # WD EDIT END
